version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 93udegef
      POSTGRES_USER: app
      POSTGRES_DB: app


    ports:
      - '5432:5432'